version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
      - ls -l target
  post_build:
    commands:
      - echo Build completed successfully
      - ls -l target
artifacts:
  files:
    - target/*.war
  discard-paths: yes
